apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: buildversions
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: "buildversions.local"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: buildversions
            port:
              number: 80
  - host: "buildversions"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: buildversions
            port:
              number: 80
